### PR TITLE
complete singin complete singup, compelet Getting

### PR DESCRIPTION
**Pull request by baishakhi-jui**
singin, singup, getting

### CODE REVIEW

**Comment by baishakhi-jui** [comment]
Naim,Ridoy,Siam,Sohag,Jui

**Review by SohagHossain9983 — CHANGES_REQUESTED** [review]
Please remove comment code

**Review by naimuddin374 — APPROVED** [review]
Looks good

**Review by naimuddin374 — APPROVED** [review]

**Review by SohagHossain9983 — APPROVED** [review]
thank to change .look good

**Pull request merged**
